name: LetterQuest
options:
  bundleIdPrefix: com.persukibo.letterquest
  deploymentTarget:
    iOS: "17.0"
  defaultConfig: Debug

packages:
  RxSwift:
    url: https://github.com/ReactiveX/RxSwift
    from: 6.7.1

targets:
  LetterQuest:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - LetterQuest
    dependencies:
      - package: RxSwift
        product: RxSwift
      - package: RxSwift
        product: RxCocoa
      - package: RxSwift
        product: RxRelay
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.persukibo.letterquest
        PROVISIONING_PROFILE_SPECIFIER: ""
        CURRENT_PROJECT_VERSION: 3
        MARKETING_VERSION: "2026"
        DEVELOPMENT_TEAM: ENT89NLKC9
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: "NO"
        INFOPLIST_FILE: LetterQuest/Resources/Info.plist
        SWIFT_VERSION: "5.9"

  LetterQuestTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - LetterQuestTests
    dependencies:
      - target: LetterQuest
      - package: RxSwift
        product: RxBlocking
    settings:
      base:
        DEVELOPMENT_TEAM: ENT89NLKC9
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: "6.0"
        GENERATE_INFOPLIST_FILE: "YES"

  LetterQuestUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - LetterQuestUITests
    dependencies:
      - target: LetterQuest
    settings:
      base:
        DEVELOPMENT_TEAM: ENT89NLKC9
        CODE_SIGN_STYLE: Automatic
        TEST_TARGET_NAME: LetterQuest
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: "YES"

configs:
  Debug: debug
  Release: release
