import Foundation

/// The category of feedback generated by a scoring signal.
enum FeedbackType {
    /// The child drew strokes in the wrong order or direction.
    case strokeOrder
    /// The overall shape of the letter was poor.
    case shape
    /// The letter did not respect ascender/descender/baseline guides.
    case proportion
    /// The strokes were shaky or drawn at uneven speed.
    case smoothness
    /// All signals passed — positive reinforcement.
    case encouragement
}

/// A single piece of feedback produced by the assessment pipeline.
protocol FeedbackItemProtocol {
    /// The scoring signal that generated this item.
    var type: FeedbackType { get }
    /// A child-friendly message to display in the UI.
    var message: String { get }
}

/// The complete result of assessing one drawing attempt.
///
/// All scores are in the range **0–100**. `passed` is `true` when `overallScore >= 75`.
/// Conforming types are immutable value types.
protocol AssessmentResultProtocol {
    /// Weighted composite score: stroke 35 % + shape 35 % + proportion 20 % + smoothness 10 %.
    var overallScore: Int { get }

    /// Score from `DTWMatcher` — stroke order and path similarity.
    var strokeOrderScore: Int { get }

    /// Score from `ShapeAnalyzer` — pixel-level IoU against the reference bitmap.
    var shapeScore: Int { get }

    /// Score from `ProportionChecker` — baseline, height, and width geometry.
    var proportionScore: Int { get }

    /// Score from `SmoothnessAnalyzer` — angular jitter and speed variance.
    var smoothnessScore: Int { get }

    /// Ordered list of feedback items. The most important item is first.
    var feedback: [FeedbackItem] { get }

    /// `true` when `overallScore >= 75`; unlocks the next letter.
    var passed: Bool { get }
}
